print("##############################")
print("#                            #")
print("#     Eric Nanda Ferdian     #")
print("#       2210817210010        #")
print("#                            #")
print("##############################")